version: '3.8'

services: 
  db: 
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
    - 5433:${TYPEORM_PORT}

  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    
  account:
    build:
      context: .
      dockerfile: ./apps/account/Dockerfile
    command: npm run start:dev account
    depends_on: 
      db:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      DATABASE_URL: postgres://root:root@db:5432/catalog  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - catalog  

  cart:
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
    command: npm run start:dev cart
    depends_on: 
      - db
      - kafka
    environment:
      DATABASE_URL: postgres://root:root@db:5432/catalog
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - catalog   

  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    command: npm run start:dev order
    depends_on: 
      - db
      - kafka
    environment:
      DATABASE_URL: postgres://root:root@db:5432/catalog
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - catalog      
    
  products:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    command: npm run start:dev products
    depends_on: 
      - db
      - kafka
    environment:
      DATABASE_URL: postgres://root:root@db:5432/catalog
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - catalog      

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: npm run start:dev api-gateway
    depends_on: 
      - db
    ports: 
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - catalog       

networks:
  catalog:
    driver:  bridge