version: '3.8'

services: 
  db: 
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
    - 5433:${TYPEORM_PORT}

  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    